'*******************************************************************************
' EverEdit Syntax File
' Language:    Java
' Maintainer:  www.everedit.net  
' History:
'   2012/04/19 **Don't modify this file!**
'*******************************************************************************
Include( ".\const.mac" )

Set java=CreateParser()
Set java_creator=java
Set rJavaRegion=java.DefaultRegion

Include( ".\java_base.mac" )
