filepath=App.ShowFileDialog(True, "", "*.jpg;*.jpeg;*.jpe;*.png;*.gif;*.bmp")
If Len(filepath) Then
	On Error Resume Next
	Set objImg = CreateObject("WIA.ImageFile")
	If objImg Is Nothing Then
		App.ShowMsgBox "Could not create WIA.ImageFile object!", "Error", 0
	Else
		objImg.LoadFile filepath
		snippet = "<img src=""" & filepath & """ width=""" & objImg.Width & """ height=""" & objImg.Height & """ border=""0"" alt="""">"
		App.ActiveDoc.Insert snippet
	End If
End If
